import Head from 'next/head'
import Footer from '../lib/component/Footer'
import { MdCode, MdPerson } from "react-icons/md";
import AlignItems from '../lib/style/AlignItems';
import Button from '../lib/component/Button';
import Banner from '../lib/component/Banner';
import BodyMargin from '../lib/style/BodyMargin';

export default function About() {
    return (
        <div className={'container'}>
            <Head>
                <title>About</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <BodyMargin>
                <div className={'grid-1fr-1fr'}>
                    <section>
                        <h1>DEIZUについて</h1>
                        <h3>利用規約・開発について</h3>
                    </section>
                    <div>
                        <Banner type="notice">
                            <p style={{margin:0}}>
                                利用規約は誰が見ても理解出来るほどわかりやすくする必要があると考えています。多くの場合長く回りくどく書かれているものをあえてわかりやすくシンプルに書きました。本サイトを使用する際はよく読んで、同意した上で使用してください。
                            </p>
                        </Banner>
                        <h2>利用規約</h2>
                        <p>
                            当サイトの名前は2021年7月17日をもちまして「DEIZU」となりました。
                            <br/>
                            サービスのご利用の際、以下の通りプライバシーポリシーを定めます。
                        </p>
                        <h3>使用される上で保存される情報</h3>
                        <p>基本的にはDEIZU本サイトに入力する情報のみ保存されます</p>
                        <ul>
                            <li>GoogleアカウントのEmail</li>
                            <li>時間割表のタイトル</li>
                            <li>時間割表のを最後編集した日にちと時間</li>
                            <li>時間割表等のメタデータ：入力した科目・URL・概要・色等</li>
                        </ul>

                        <h3>情報収集の目的について</h3>
                        <p>事前にユーザーに通知することなく、本ポリシーを改訂する場合が有りますのでご了承下さい。</p>
                        <ol>
                            <li>個々のユーザーに適したサービスを提供するため</li>
                            <li>当サイトの改善・新たなサービスの開発のため</li>
                            <li>お問い合わせやその他のご連絡などに対応するため</li>
                        </ol>
                        <h3>当サイトで利用している第三者サービス</h3>
                        <p>当サイトは以下の第三者サービスを利用します。</p>
                        <h4>Google Analytics</h4>
                        <p>当サイトを使用する際は匿名で場所と閲覧時間などが今後の改善の為に記録されます。</p>
                        <h4>Firebase (Google Cloud Platform)</h4>
                        <p>当サイトは、Firebase (Google Cloud Platform) を通してアカウント・当サイトのデータを管理させていただいています。ログインし使用する際はFirebaseにデータが保存されます。</p>
                        <p>
                            ※Google Inc.の<a href="https://policies.google.com/technologies/partner-sites?hl=ja">プライバシーポリシー</a>
                        </p>
                        <hr />
                        <h2>開発について</h2>
                        <p>裏で動作している状況はユーザーを含め誰にでも閲覧できるようにしています。このようにオープンソースにすることでセキュリティーに関するリスクや機能の追加状況を目で確認することができます。ソースコードは全てGitHubに有り、以下のリンクからアクセスが可能です：</p>
                        <AlignItems>
                            <Button
                                onClick={() => { window.open('https://github.com/501A-Designs/DEIZU', "_blank") }}
                                icon={<MdCode/>}
                            >
                                GitHubを見る
                            </Button>
                            <Button
                                onClick={() => { window.open('https://501a.netlify.app', "_blank") }}
                                icon={<MdPerson/>}
                            >
                                開発者のサイト
                            </Button>
                        </AlignItems>
                        <br/>
                        <h3>テクノロジースタック</h3>
                        <h4>ウェブプラットフォーム</h4>
                        <ul>
                            <ol>Next JS</ol>
                        </ul>
                        <h4>モバイルアプリ：iOSとAndroid版</h4>
                        <ul>
                            <ol>React Native</ol>
                        </ul>
                        <h4>バックエンド</h4>
                        <p>Webとモバイル版は両方同じFirebaseをバックエンドで使用しております。</p>
                        <ul>
                            <ol>Firebase：ユーザーデータとログインの管理システム（BAAS）</ol>
                            <ul>
                                <ol>Firestore (Google Cloud Platform)：ユーザーデータのデータベース</ol>
                                <ol>Authentication：ログインシステム</ol>
                            </ul>
                        </ul>
                        <p>バージョン情報については<a href="https://github.com/501A-Designs/DEIZU/releases">GitHubのリリース</a>でも確認することができます</p>
                    </div>
                </div>
            </BodyMargin>
            <Footer />
        </div>
    )
}
