import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import { BrowserMockup } from 'react-mockup'
import 'react-mockup/dist/index.css'
import Header from './Header'
import { MdOutlineOpenInBrowser,MdCode } from "react-icons/md";

export default function Home() {
  const [versionData, setVersionData] = useState();

  return (
    <div className={'container'}>
      <Head>
        <title>DEIZU</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header/>

      <main className={styles.main}>
        <div className={styles.duoGrid}>
          <section className={styles.padding2em}>
            <h2>時間割をすばやく作成</h2>
            <div className={styles.headStyle}>
              <h1>DEIZU</h1>
              {/* <span>v{versionData}</span> */}
            </div>
            <div className={styles.buttonGap}>
              <button className={styles.blueBtn} onClick={() => { window.open('https://deizu-site.firebaseapp.com/', "_blank") }}><MdOutlineOpenInBrowser className={styles.icon}/>アプリを開く</button>
              <button className={styles.whiteBtn} onClick={() => { window.open('https://github.com/501A-Designs/DEIZU', "_blank") }}><MdCode className={styles.icon}/>GitHubを見る</button>
            </div>
          </section>
          <section className="mockupContainer">
            <BrowserMockup
              src="/deizu-screenshot.png"
              type="mac"
              color="black"
            />
          </section>
        </div>

        <div className={styles.duoGrid}>
          <section>
            <ul>
              <li>使いやすい UI</li>
              <li>Google アカウントでログイン</li>
              <li>端末問わず使用可能（Web 上）</li>
              <li>科目のセルの色、リンク、概要欄可</li>
              <li>時間割の時間を指定</li>
              <li>何枚もの時間割表を作成・保存可</li>
            </ul>
          </section>
          <section className={styles.padding2em}>
            <h1 className={styles.title}>どシンプルがいいのだ</h1>
            <h2>シンプルで使いやすい時間割表作成サイト</h2>
            <p className={styles.description}>
              このソフトは時間割表の作りづらさを改善しようと考えられ開発されたソフトです。シンプルなデザインと共に紙で作成するマニュアルなプロセスやスプレッドシートやExcelを使用する際にテンプレートを作成する作業を全て排除します！
            </p>
          </section>
        </div>


        <div className={styles.duoGrid}>
          <section className={styles.padding2em}>
            <h1 className={styles.title}>カスタマイズ仕放題</h1>
            <h2>壁紙の指定可 &rarr;</h2>
            <h2>テーマの変更可 &rarr;</h2>
            <h2>色の変更可 &rarr;</h2>
          </section>
          <div className={styles.carousel}>
            <div className={styles.card}>
              <BrowserMockup src="/deizu-browntheme.png" />
            </div>
            <div className={styles.card}>
              <BrowserMockup src="/deizu-bluetheme.png" />
            </div>
            <div className={styles.card}>
              <BrowserMockup src="/deizu-greentheme.png" />
            </div>
            <div className={styles.card}>
              <BrowserMockup src="/deizu-greytheme.png" />
            </div>
            <div className={styles.card}>
              <BrowserMockup src="/deizu-orangetheme.png" />
            </div>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a href="usage">使用法</a>
        <a href="about">DEIZUについて</a>
        <a
          href="https://501a.netlify.app"
          target="_blank"
          rel="noopener noreferrer"
        >
          501A
        </a>
      </footer>
    </div >
  )
}
