import Head from 'next/head'
import Container from '../lib/component/Container'
import Heading from '../lib/component/Heading'
import LinkTag from '../lib/component/LinkTag'
import TextPreview from '../lib/component/TextPreview'
import AlignItems from '../lib/style/AlignItems'
import BodyMargin from '../lib/style/BodyMargin'
import Stack from '../lib/style/Stack'
import { BlurHeader } from '../lib/component/BlurHeader'

export default function Usage() {
  return (
    <>
      <Head>
        <title>使用法</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BlurHeader/>
      <BodyMargin>
        <AlignItems
          flexDirection={'column'}
          justifyContent={'center'}
          marginBottom={'extraLarge'}
        >
          <Heading type={'h1'}>データシートの使用法</Heading>
          <Heading type={'h4'}>ちょっとややこしい部分を解説</Heading>
        </AlignItems>
        <Container
          marginTop={'1em'}
          marginBottom={'2em'}
        >
          <Heading type={'h3'}>データシートとは？</Heading>
          <p>
            Deizuには時間割ごとでデータシートというものを追加することができます。データシートはある項目にそった科目を保存できる場所です。データシートを時間割に追加するとで科目を入力する際に表示され、時間割の入力が少し速くなります。
            <br/>
            ※例えば〇〇大学の〇〇学部の生徒がデータシートを作成すると、同じ〇〇大の〇〇学部の生徒が使うことができます。
          </p>
        </Container>
        <Heading type={'h3'}>時間割表にデータシートを追加</Heading>
        <Container
          styleType={'gradient'}
          marginTop={'0.5em'}
          marginBottom={'1.5em'}
        >
          <Heading type={'h4'}>
            時間割表から直接データシートを繋げる方法
          </Heading>
          <p>
            データシートを追加したい時間割表を開き、一番右に見られる設定のアイコンを押してください。
            <br />
            設定を開くと一番上にある、「データシートを繋げる」を押し、繋げたいデータシートをクリック。これをした後、「データシートを繋げる」と書いたボタンを押すことでデータシートが時間割表に追加されます。
            <br/>
            ※データシートにはそれぞれユニークなIDがあり、データシートのIDをコピ-する事で時間割表に追加することができます。
            <hr/>
          </p>
          <Heading type={'h4'}>
            データシートのページから追加する方法
          </Heading>
          <p>
            使いたいデータシートを開き、右側の方にある「IDをコピー」と書いてあるボタンを押すことでIDをコピーすることができます。このコピーしたIDは接続したい時間割表の設定画面に表示されるインプットに入力し、追加する事ができます。
          </p>
        </Container>
        <Heading type={'h3'}>データシートを使う上で</Heading>
        <Container
          styleType={'gradient'}
          marginTop={'0.5em'}
          marginBottom={'1.5em'}
        >
          <p>
            追加されると追加したデータシートの名前が入力した欄の上に表示され、設定を閉じ時間割表のセルを開くとデータシートに保存されている科目の一覧が表示されます。横スクロールし、追加したい科目をクリックすると科目の情報が入力されます。追加で「概要」または「URL」の部分に情報を書き込むことができ、追加で入力する情報はデータシートには共有されないので安心してください。
          </p>
        </Container>
        <Heading type={'h3'}>データシートを作成</Heading>
        <Container
          styleType={'gradient'}
          marginTop={'0.5em'}
          marginBottom={'1.5em'}
        >
          <p>
            データシート一覧のページからデータシートを新しく作成することができます（以下のURL）
          </p>
          <TextPreview>
            <LinkTag href={'/datasheet'}>deizu.vercel.app/datasheet/</LinkTag>
          </TextPreview>
        </Container>
      </BodyMargin>
    </>
  )
}
