import Head from 'next/head'
import Container from '../lib/component/Container'
import Heading from '../lib/component/Heading'
import LinkTag from '../lib/component/LinkTag'
import NavFooter from '../lib/component/BlurHeader'
import TextPreview from '../lib/component/TextPreview'
import AlignItems from '../lib/style/AlignItems'
import BodyMargin from '../lib/style/BodyMargin'
import Stack from '../lib/style/Stack'

export default function Usage() {
  return (
    <>
      <Head>
        <title>使用法</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BodyMargin>
        <AlignItems
          flexDirection={'column'}
          justifyContent={'center'}
          marginBottom={'extraLarge'}
        >
          <Heading type={'h1'}>Deizuの使用法</Heading>
          <Heading type={'h4'}>アカウントの作成・カスタマイズ・時間割表について</Heading>
        </AlignItems>
        <Heading type={'h2'}>アカウントについて</Heading>
        <Heading type={'h3'}>新規登録・ログイン</Heading>
        <p>
          <LinkTag href="/app">deizu.vercel.app/app/</LinkTag>から、Googleでログインのボタンを押すことで登録されているGoogleアカウントで簡単にアカウントを作成・ログインすることができます。
        </p>
        <Heading type={'h3'}>ログアウト</Heading>
        <p>
          ダッシュボードの画面の左手にユーザー様のプロフィール画像がありますのでそちらをクリックしてもらうとログアウトボタンがある画面に進むことができるので、そちらを押すとログアウトすることができます。
        </p>
        <Heading type={'h3'}>カスタマイズ</Heading>
        <p>
          ダッシュボードの左手にユーザー様のお名前と画像が表示される部分があります。そちらからみた右にパレットのアイコンがあるので、そちらを押すことでカスタマイズ設定（見た目の変更）を行うことができます。なお、以下の操作をすることができます：
        </p>
        <ul>
          <li>ユーザー様のバナー画像の指定</li>
          <li>テーマの変更：5種類</li>
          <li>色を変更：8種類</li>
        </ul>
        <p>
          なお、時間割それぞれには独自の「バナー画像の指定」と「壁紙の指定」を行うこともできます。（時間割を開き設定から追加・変更を行うことができます。）
        </p>
        <hr />
        <Heading type={'h2'}>時間割表について</Heading>
        <Heading type={'h3'}>時間割表の開き方</Heading>
        <p>
          ログイン済みの場合は自動的にダッシュボードに移動します。ダッシュボードでは新しい表を作成というボタンがあり、過去に既に作成した場合には表がボタンの下に並べられます。
          <br />
          表のタイトルを押すことで開くことができ、タイトル以外の物全てを再び編集することができます。
        </p>
        <Heading type={'h2'}>時間割表とデータシートの使用法</Heading>
        <Heading type={'h3'}>データシートとは？</Heading>
        <p>
          Deizuには時間割ごとでデータシートというものを追加することができます。データシートはある項目にそって時間割の科目をまとまって保存されているものであり、データシートをある時間割に追加することで科目の入力がより素早くなります。
        </p>
        <Heading type={'h3'}>時間割表にデータシートを追加</Heading>
        <ol>
          <li>データシートのIDをコピー</li>
          <Container styleType={'transparent'}>
            <p>
              データシートにはそれぞれユニークなIDがあり、データシートのIDをコピする事で時間割表に追加することができます。
              <br />
              IDはデータシートの一覧のページのデータシートのボタンの左にある丸いアイコンを押すことでコピーすることができます。
              <br />
              またボタンを押しデータシートのページを開くと移動するURLの後ろの部分からもIDを抽出することができます。（下記を参照）
            </p>
            <TextPreview>
              deizu.vercel.app/datasheet/データシートID
            </TextPreview>
          </Container>
          <li>時間割表に追加</li>
          <Container styleType={'transparent'}>
            <p>
              データシートを追加したい時間割表を開き、一番右に見られる設定のアイコンを押してください。
              <br />
              設定を開くと一番上にある、「データシートを繋げる」を押し、1でコピーしたデータシートのIDをインプットに入力し「データシートを繋げる」と書いたボタンを押すとデータシートが時間割表に追加されます。
            </p>
          </Container>
          <li>確認</li>
          <Container styleType={'transparent'}>
            <p>
              追加されると追加したデータシートの名前が入力した欄の上に表示され、設定を閉じ時間割表のセルを開くとデータシートに保存されている科目の一覧が表示されます。横スクロールし、追加したい科目をクリックすると科目の情報が入力されます。
              <br />
              追加で「概要」または「URL」の部分に情報を書き込むことができ、追加で入力する情報はデータシートには共有されないので安心してください。
            </p>
          </Container>
        </ol>
        <Heading type={'h3'}>データシートを作成</Heading>
        <p>
          データシート一覧のページからデータシートを新しく作成することができます（以下のURL）
        </p>
        <TextPreview>
          deizu.vercel.app/datasheet/
        </TextPreview>
        <p>
          なおデータシート作成のページに直接飛びたい人は以下のURLで開くことができます（Deizuにログインする必要がございます。新規登録・ログインは<LinkTag href="/app">こちら</LinkTag>から）
        </p>
        <TextPreview>
          deizu.vercel.app/datasheet/create/
        </TextPreview>
      </BodyMargin>
      <NavFooter/>
    </>
  )
}
